# This ini file is a service file on linux that will change prometheus to run as a service (should work)
[Unit]
Description=Prometheus server
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=root
WorkingDirectory=/root/prometheus
ExecStart=/root/prometheus/prometheus

[Install]
WantedBy=multi-user.target
